-- Generated by Pywal
hl.config({{
    general = {{
        col = {{
            active_border = "rgb({color1.strip})",
            inactive_border = "rgb({color0.strip})",
        }},
    }},
    decoration = {{
        shadow = {{
            color = "rgba({color0.strip}ee)",
        }},
    }},
}})
